# Generated by Django 4.0.4 on 2023-09-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='NULL', max_length=255, unique=True),
        ),
    ]
